image:
  name: nishtahir/openjfx:8-jdk

stages:
- build
- test
- deploy

unit-test-job:
  stage: test
  script:
    - mkdir build
    - find -name "*.java" > sources.txt
    - wget "https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar"
    #- wget "https://mvnrepository.com/artifact/io.github.typhon0/AnimateFX/1.2.1/"
    - javac -cp "junit-platform-console-standalone-1.8.2.jar:/usr/lib/jvm/openjfx/javafx-swt.jar:/usr/lib/jvm/openjfx/javafx.web.jar:/usr/lib/jvm/openjfx/javafx.base.jar:/usr/lib/jvm/openjfx/javafx.fxml.jar:/usr/lib/jvm/openjfx/javafx.media.jar:/usr/lib/jvm/openjfx/javafx.swing.jar:/usr/lib/jvm/openjfx/javafx.controls.jar:/usr/lib/jvm/openjfx/javafx.graphics.jar" -d build @sources.txt
    - 'printf "Manifest-Version: 1.0\nMain-Class: wordle.JarRunner" > MANIFEST.MF'
    - jar cmvf MANIFEST.MF jarfile.jar build/*
    #- java -jar junit-platform-console-standalone-1.8.2.jar $CI_PROJECT_DIR/src/Testing/ModelTesting.java
  artifacts:
    paths:
      - "jarfile.jar"
    expire_in: 1 day

deploy-job:
  stage: deploy
  script:
    - echo "Deploying"
    
include:
- template: Security/SAST.gitlab-ci.yml
