image:
  name: nishtahir/openjfx:8-jdk

stages:
- build
- test
- deploy

unit-test-job:
  stage: test
  script:
    - mkdir build
    - find -name "*.java" > sources.txt
    - javac -d build @sources.txt
    - jar cvf jarfile.jar build/*
    #- wget "https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar"
    #- java -jar junit-platform-console-standalone-1.8.2.jar $CI_PROJECT_DIR/src/Testing/ModelTesting.java
  artifacts:
    paths:
      - "jarfile.jar"
    expire_in: 1 day

deploy-job:
  stage: deploy
  script:
    - echo "Deploying"
    
include:
- template: Security/SAST.gitlab-ci.yml
