stages:
- build
- test
- deploy

build-job:
  stage: build
  script:
    - mkdir build/
    - echo "My application binary file" > build/project-executable # Imagine this is a real file
  artifacts:
    paths:
      - build/project-executable

unit-test-job:
  stage: test
  script:
    - echo "hello"
    - cat $CI_PROJECT_DIR/build/project-executable #Get to the file

deploy-job:
  stage: deploy
  script:
    - echo "Deploying"
    
include:
- template: Security/SAST.gitlab-ci.yml
